### ISSUE TITLE
سلام

### ISSUE THREAD

**Issue by jeilun** [HassanHeydariNasab/speedshow#1]
سلام
مهندس شما پروژه spirt fm radio  کار کردی ؟

ممنون میشم اگر بتونیم یک همکاری با هم داشته باشیم 

mrparnian@live.com

09171907534

**Comment by HassanHeydariNasab** [comment]
سلام
نه. فقط یک درخواست داده بودم برای اضافه کردن پشتیبانیش از گوشیم.
